# Generated by Django 5.1.2 on 2024-11-09 14:07

import farmers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_id',
            field=models.CharField(default=farmers.models.generate_farmer_id, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='date_reported',
            field=models.DateTimeField(),
        ),
    ]
